export type Expense = {
  id: string;
  branch: 'Boys' | 'Girls' | 'Hostel';
  type: 'Salary' | 'Food' | 'Utility';
  note: string;
  addedBy: string;
  date: string;
  amount: number;
};

export const allExpenses: Expense[] = [
  {
    id: '1',
    branch: 'Boys',
    type: 'Salary',
    note: 'Monthly salary for teachers and staff',
    addedBy: 'Admin User',
    date: '2024-01-15',
    amount: 45000,
  },
  {
    id: '2',
    branch: 'Boys',
    type: 'Food',
    note: 'Daily meals for students and staff',
    addedBy: 'Admin User',
    date: '2024-01-14',
    amount: 8500,
  },
  {
    id: '3',
    branch: 'Girls',
    type: 'Utility',
    note: 'Electricity bill for January',
    addedBy: 'Admin User',
    date: '2024-01-13',
    amount: 12000,
  },
  {
    id: '4',
    branch: 'Boys',
    type: 'Salary',
    note: 'Part-time teacher salary',
    addedBy: 'Admin User',
    date: '2024-01-12',
    amount: 15000,
  },
  {
    id: '5',
    branch: 'Girls',
    type: 'Food',
    note: 'Weekly grocery shopping',
    addedBy: 'Admin User',
    date: '2024-01-11',
    amount: 3200,
  },
  {
    id: '6',
    branch: 'Boys',
    type: 'Utility',
    note: 'Water bill payment',
    addedBy: 'Admin User',
    date: '2024-01-10',
    amount: 2500,
  },
  {
    id: '7',
    branch: 'Girls',
    type: 'Salary',
    note: 'Security guard salary',
    addedBy: 'Admin User',
    date: '2024-01-09',
    amount: 8000,
  },
  {
    id: '8',
    branch: 'Boys',
    type: 'Food',
    note: 'Cafeteria supplies and ingredients',
    addedBy: 'Admin User',
    date: '2024-01-08',
    amount: 4500,
  },
  {
    id: '9',
    branch: 'Girls',
    type: 'Utility',
    note: 'Internet and phone bills',
    addedBy: 'Admin User',
    date: '2024-01-07',
    amount: 3500,
  },
  {
    id: '10',
    branch: 'Boys',
    type: 'Salary',
    note: 'Cleaner and maintenance staff salary',
    addedBy: 'Admin User',
    date: '2024-01-06',
    amount: 12000,
  },
  {
    id: '11',
    branch: 'Boys',
    type: 'Food',
    note: 'Special meal for religious events',
    addedBy: 'Admin User',
    date: '2024-01-05',
    amount: 2800,
  },
  {
    id: '12',
    branch: 'Boys',
    type: 'Utility',
    note: 'Gas bill for cooking',
    addedBy: 'Admin User',
    date: '2024-01-04',
    amount: 1800,
  },
  {
    id: '13',
    branch: 'Girls',
    type: 'Salary',
    note: 'Administrative staff salary',
    addedBy: 'Admin User',
    date: '2024-01-03',
    amount: 22000,
  },
  {
    id: '14',
    branch: 'Boys',
    type: 'Food',
    note: 'Monthly food supplies bulk purchase',
    addedBy: 'Admin User',
    date: '2024-01-02',
    amount: 15000,
  },
  {
    id: '15',
    branch: 'Boys',
    type: 'Utility',
    note: 'Generator fuel and maintenance',
    addedBy: 'Admin User',
    date: '2024-01-01',
    amount: 5000,
  },
  {
    id: '16',
    branch: 'Boys',
    type: 'Salary',
    note: 'Imam and religious teacher salary',
    addedBy: 'Admin User',
    date: '2023-12-31',
    amount: 18000,
  },
  {
    id: '17',
    branch: 'Girls',
    type: 'Food',
    note: 'Festival meal preparation',
    addedBy: 'Admin User',
    date: '2023-12-30',
    amount: 4200,
  },
  {
    id: '18',
    branch: 'Boys',
    type: 'Utility',
    note: 'Building maintenance and repairs',
    addedBy: 'Admin User',
    date: '2023-12-29',
    amount: 8500,
  },
  {
    id: '19',
    branch: 'Girls',
    type: 'Salary',
    note: 'Driver salary for school transport',
    addedBy: 'Admin User',
    date: '2023-12-28',
    amount: 10000,
  },
  {
    id: '20',
    branch: 'Boys',
    type: 'Food',
    note: 'Emergency food supplies',
    addedBy: 'Admin User',
    date: '2023-12-27',
    amount: 3500,
  },
];
