export type Income = {
  id: string;
  branch: 'Boys' | 'Girls';
  type: 'Admission Fee' | 'Session Fee' | "Students' Monthly Fee" | 'Canteen' | 'Others';
  note: string;
  addedBy: string;
  date: string;
  amount: number;
};

export const allIncomes: Income[] = [
  {
    id: '1',
    branch: 'Boys',
    type: "Students' Monthly Fee",
    note: 'Monthly tuition fees collected from the boys branch.',
    addedBy: 'Admin User',
    date: '2024-01-15',
    amount: 25000,
  },
  {
    id: '2',
    branch: 'Boys',
    type: 'Admission Fee',
    note: 'Admission charges for new students joining mid-year.',
    addedBy: 'Admin User',
    date: '2024-01-14',
    amount: 5000,
  },
  {
    id: '3',
    branch: 'Girls',
    type: 'Session Fee',
    note: 'Session renewal fees for the academic term.',
    addedBy: 'Admin User',
    date: '2024-01-13',
    amount: 15000,
  },
  {
    id: '4',
    branch: 'Boys',
    type: 'Canteen',
    note: 'Canteen snack sales during events.',
    addedBy: 'Admin User',
    date: '2024-01-12',
    amount: 8000,
  },
  {
    id: '5',
    branch: 'Girls',
    type: 'Admission Fee',
    note: 'Admission processing fees for transfer students.',
    addedBy: 'Admin User',
    date: '2024-01-11',
    amount: 3200,
  },
  {
    id: '6',
    branch: 'Boys',
    type: 'Session Fee',
    note: 'Session fees collected for exam season.',
    addedBy: 'Admin User',
    date: '2024-01-10',
    amount: 12000,
  },
  {
    id: '7',
    branch: 'Girls',
    type: 'Canteen',
    note: 'Cafeteria revenue from daily sales.',
    addedBy: 'Admin User',
    date: '2024-01-09',
    amount: 4500,
  },
  {
    id: '8',
    branch: 'Boys',
    type: 'Others',
    note: 'Sale of educational materials and stationery items.',
    addedBy: 'Admin User',
    date: '2024-01-08',
    amount: 2800,
  },
  {
    id: '9',
    branch: 'Girls',
    type: "Students' Monthly Fee",
    note: 'Monthly tuition fees collected from the girls branch.',
    addedBy: 'Admin User',
    date: '2024-01-07',
    amount: 18000,
  },
  {
    id: '10',
    branch: 'Boys',
    type: 'Others',
    note: 'Guest lecture ticket sales.',
    addedBy: 'Admin User',
    date: '2024-01-06',
    amount: 3500,
  },
  {
    id: '11',
    branch: 'Girls',
    type: 'Admission Fee',
    note: 'Admission packet purchases for applicants.',
    addedBy: 'Admin User',
    date: '2024-01-05',
    amount: 4200,
  },
  {
    id: '12',
    branch: 'Boys',
    type: 'Session Fee',
    note: 'Examination session fees received from students.',
    addedBy: 'Admin User',
    date: '2024-01-04',
    amount: 9500,
  },
  {
    id: '13',
    branch: 'Girls',
    type: 'Others',
    note: 'Workshop and seminar registration fees.',
    addedBy: 'Admin User',
    date: '2024-01-03',
    amount: 6200,
  },
  {
    id: '14',
    branch: 'Boys',
    type: 'Admission Fee',
    note: 'Admission documentation charges.',
    addedBy: 'Admin User',
    date: '2024-01-02',
    amount: 3800,
  },
  {
    id: '15',
    branch: 'Girls',
    type: 'Session Fee',
    note: 'Library session fees collected for renewals.',
    addedBy: 'Admin User',
    date: '2024-01-01',
    amount: 1500,
  },
  {
    id: '16',
    branch: 'Boys',
    type: 'Others',
    note: 'Photocopy and printing service charges.',
    addedBy: 'Admin User',
    date: '2023-12-31',
    amount: 2100,
  },
  {
    id: '17',
    branch: 'Girls',
    type: 'Canteen',
    note: 'Seasonal canteen stall earnings.',
    addedBy: 'Admin User',
    date: '2023-12-30',
    amount: 1800,
  },
  {
    id: '18',
    branch: 'Boys',
    type: "Students' Monthly Fee",
    note: 'Hostel accommodation monthly dues.',
    addedBy: 'Admin User',
    date: '2023-12-29',
    amount: 22000,
  },
  {
    id: '19',
    branch: 'Girls',
    type: 'Others',
    note: 'Special event ticket sales.',
    addedBy: 'Admin User',
    date: '2023-12-28',
    amount: 7500,
  },
  {
    id: '20',
    branch: 'Boys',
    type: 'Admission Fee',
    note: 'Late admission form fees.',
    addedBy: 'Admin User',
    date: '2023-12-27',
    amount: 2900,
  },
];
