export type Income = {
  id: string;
  type: 'Student Fee' | 'Book Sell' | 'Other';
  note: string;
  addedBy: string;
  date: string;
  amount: number;
};

export const allIncomes: Income[] = [
  {
    id: '1',
    type: 'Student Fee',
    note: 'Monthly fee collection from students',
    addedBy: 'Admin User',
    date: '2024-01-15',
    amount: 25000,
  },
  {
    id: '2',
    type: 'Book Sell',
    note: 'Islamic books and study materials sold',
    addedBy: 'Admin User',
    date: '2024-01-14',
    amount: 5000,
  },
  {
    id: '3',
    type: 'Student Fee',
    note: 'Admission fee collection',
    addedBy: 'Admin User',
    date: '2024-01-13',
    amount: 15000,
  },
  {
    id: '4',
    type: 'Other',
    note: 'Fundraising event proceeds',
    addedBy: 'Admin User',
    date: '2024-01-12',
    amount: 8000,
  },
  {
    id: '5',
    type: 'Book Sell',
    note: 'Quran and Hadith books sold',
    addedBy: 'Admin User',
    date: '2024-01-11',
    amount: 3200,
  },
  {
    id: '6',
    type: 'Student Fee',
    note: 'Transportation fee collection',
    addedBy: 'Admin User',
    date: '2024-01-10',
    amount: 12000,
  },
  {
    id: '7',
    type: 'Other',
    note: 'Cafeteria income',
    addedBy: 'Admin User',
    date: '2024-01-09',
    amount: 4500,
  },
  {
    id: '8',
    type: 'Book Sell',
    note: 'Educational materials and stationery',
    addedBy: 'Admin User',
    date: '2024-01-08',
    amount: 2800,
  },
  {
    id: '9',
    type: 'Student Fee',
    note: 'Monthly tuition fee',
    addedBy: 'Admin User',
    date: '2024-01-07',
    amount: 18000,
  },
  {
    id: '10',
    type: 'Other',
    note: 'Guest lecture fee collection',
    addedBy: 'Admin User',
    date: '2024-01-06',
    amount: 3500,
  },
  {
    id: '11',
    type: 'Book Sell',
    note: 'Religious literature sales',
    addedBy: 'Admin User',
    date: '2024-01-05',
    amount: 4200,
  },
  {
    id: '12',
    type: 'Student Fee',
    note: 'Examination fee collection',
    addedBy: 'Admin User',
    date: '2024-01-04',
    amount: 9500,
  },
  {
    id: '13',
    type: 'Other',
    note: 'Workshop and seminar fees',
    addedBy: 'Admin User',
    date: '2024-01-03',
    amount: 6200,
  },
  {
    id: '14',
    type: 'Book Sell',
    note: 'Arabic learning books sold',
    addedBy: 'Admin User',
    date: '2024-01-02',
    amount: 3800,
  },
  {
    id: '15',
    type: 'Student Fee',
    note: 'Library membership fee',
    addedBy: 'Admin User',
    date: '2024-01-01',
    amount: 1500,
  },
  {
    id: '16',
    type: 'Other',
    note: 'Photocopy and printing services',
    addedBy: 'Admin User',
    date: '2023-12-31',
    amount: 2100,
  },
  {
    id: '17',
    type: 'Book Sell',
    note: 'Islamic calendar and prayer books',
    addedBy: 'Admin User',
    date: '2023-12-30',
    amount: 1800,
  },
  {
    id: '18',
    type: 'Student Fee',
    note: 'Hostel accommodation fee',
    addedBy: 'Admin User',
    date: '2023-12-29',
    amount: 22000,
  },
  {
    id: '19',
    type: 'Other',
    note: 'Special event ticket sales',
    addedBy: 'Admin User',
    date: '2023-12-28',
    amount: 7500,
  },
  {
    id: '20',
    type: 'Book Sell',
    note: 'Islamic history and biography books',
    addedBy: 'Admin User',
    date: '2023-12-27',
    amount: 2900,
  },
];
